version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=host.docker.internal  # Update with your MySQL host
      - MYSQL_DATABASE=tdm  # Update with your MySQL database name
      - MYSQL_USER=root  # Update with your MySQL username
      - MYSQL_PASSWORD=123  # Update with your MySQL password
